/* Generated by tools/gen_opentls_headers.py: do not edit. MIT, (c) 2026 Dalsin Limited. */
#ifndef CLIB_OPENTLS_PROTOS_H
#define CLIB_OPENTLS_PROTOS_H

#include <exec/types.h>
#include <exec/libraries.h>
#include <libraries/opentls.h>

ULONG OT_Version(VOID);
struct OTContext * OT_NewContext(CONST struct OTContextConfig *config, LONG *error);
VOID OT_FreeContext(struct OTContext *context);
LONG OT_AddTrustFile(struct OTContext *context, CONST_STRPTR path);
LONG OT_AddTrustPEM(struct OTContext *context, CONST_APTR pem, LONG length);
struct OTConnection * OT_NewConnection(struct OTContext *context, CONST_STRPTR hostname, LONG *error);
VOID OT_FreeConnection(struct OTConnection *connection);
LONG OT_SetSocket(struct OTConnection *connection, LONG socket, struct Library *socketBase);
LONG OT_SetIOHook(struct OTConnection *connection, struct Hook *hook);
LONG OT_SetALPN(struct OTConnection *connection, CONST_STRPTR protocols);
LONG OT_SetVerify(struct OTConnection *connection, LONG mode);
LONG OT_PinCertificate(struct OTConnection *connection, CONST UBYTE *sha256);
LONG OT_SetSession(struct OTConnection *connection, struct OTSession *session);
LONG OT_Handshake(struct OTConnection *connection);
LONG OT_Read(struct OTConnection *connection, APTR buffer, LONG length);
LONG OT_Write(struct OTConnection *connection, CONST_APTR buffer, LONG length);
LONG OT_Pending(struct OTConnection *connection);
LONG OT_Close(struct OTConnection *connection);
struct OTSession * OT_GetSession(struct OTConnection *connection);
VOID OT_FreeSession(struct OTSession *session);
LONG OT_SessionResumed(struct OTConnection *connection);
LONG OT_GetError(struct OTConnection *connection);
CONST_STRPTR OT_GetErrorText(struct OTConnection *connection);
CONST_STRPTR OT_ErrorString(LONG error);
LONG OT_GetProtocol(struct OTConnection *connection);
CONST_STRPTR OT_GetCipher(struct OTConnection *connection);
CONST_STRPTR OT_GetALPN(struct OTConnection *connection);
LONG OT_GetPeerFingerprint(struct OTConnection *connection, UBYTE *sha256);
LONG OT_GetPeerCertificate(struct OTConnection *connection, APTR buffer, LONG length);
LONG OT_Random(APTR buffer, LONG length);
ULONG OT_Accelerated(VOID);
LONG OT_GetErrorDetail(struct OTConnection *connection);

#endif
