/* Generated by tools/gen_opentls_headers.py: do not edit. MIT, (c) 2026 Dalsin Limited. */
#ifndef INLINE_OPENTLS_H
#define INLINE_OPENTLS_H

#ifndef __INLINE_MACROS_H
#include <inline/macros.h>
#endif

#ifndef OPENTLS_BASE_NAME
#define OPENTLS_BASE_NAME OpenTLSBase
#endif

#define OT_Version() \
	LP0(0x1e, ULONG, OT_Version, , OPENTLS_BASE_NAME)

#define OT_NewContext(config, error) \
	LP2(0x24, struct OTContext *, OT_NewContext, CONST struct OTContextConfig *, config, a0, LONG *, error, a1, , OPENTLS_BASE_NAME)

#define OT_FreeContext(context) \
	LP1NR(0x2a, OT_FreeContext, struct OTContext *, context, a0, , OPENTLS_BASE_NAME)

#define OT_AddTrustFile(context, path) \
	LP2(0x30, LONG, OT_AddTrustFile, struct OTContext *, context, a0, CONST_STRPTR, path, a1, , OPENTLS_BASE_NAME)

#define OT_AddTrustPEM(context, pem, length) \
	LP3(0x36, LONG, OT_AddTrustPEM, struct OTContext *, context, a0, CONST_APTR, pem, a1, LONG, length, d0, , OPENTLS_BASE_NAME)

#define OT_NewConnection(context, hostname, error) \
	LP3(0x3c, struct OTConnection *, OT_NewConnection, struct OTContext *, context, a0, CONST_STRPTR, hostname, a1, LONG *, error, a2, , OPENTLS_BASE_NAME)

#define OT_FreeConnection(connection) \
	LP1NR(0x42, OT_FreeConnection, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_SetSocket(connection, socket, socketBase) \
	LP3(0x48, LONG, OT_SetSocket, struct OTConnection *, connection, a0, LONG, socket, d0, struct Library *, socketBase, a1, , OPENTLS_BASE_NAME)

#define OT_SetIOHook(connection, hook) \
	LP2(0x4e, LONG, OT_SetIOHook, struct OTConnection *, connection, a0, struct Hook *, hook, a1, , OPENTLS_BASE_NAME)

#define OT_SetALPN(connection, protocols) \
	LP2(0x54, LONG, OT_SetALPN, struct OTConnection *, connection, a0, CONST_STRPTR, protocols, a1, , OPENTLS_BASE_NAME)

#define OT_SetVerify(connection, mode) \
	LP2(0x5a, LONG, OT_SetVerify, struct OTConnection *, connection, a0, LONG, mode, d0, , OPENTLS_BASE_NAME)

#define OT_PinCertificate(connection, sha256) \
	LP2(0x60, LONG, OT_PinCertificate, struct OTConnection *, connection, a0, CONST UBYTE *, sha256, a1, , OPENTLS_BASE_NAME)

#define OT_SetSession(connection, session) \
	LP2(0x66, LONG, OT_SetSession, struct OTConnection *, connection, a0, struct OTSession *, session, a1, , OPENTLS_BASE_NAME)

#define OT_Handshake(connection) \
	LP1(0x6c, LONG, OT_Handshake, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_Read(connection, buffer, length) \
	LP3(0x72, LONG, OT_Read, struct OTConnection *, connection, a0, APTR, buffer, a1, LONG, length, d0, , OPENTLS_BASE_NAME)

#define OT_Write(connection, buffer, length) \
	LP3(0x78, LONG, OT_Write, struct OTConnection *, connection, a0, CONST_APTR, buffer, a1, LONG, length, d0, , OPENTLS_BASE_NAME)

#define OT_Pending(connection) \
	LP1(0x7e, LONG, OT_Pending, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_Close(connection) \
	LP1(0x84, LONG, OT_Close, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_GetSession(connection) \
	LP1(0x8a, struct OTSession *, OT_GetSession, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_FreeSession(session) \
	LP1NR(0x90, OT_FreeSession, struct OTSession *, session, a0, , OPENTLS_BASE_NAME)

#define OT_SessionResumed(connection) \
	LP1(0x96, LONG, OT_SessionResumed, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_GetError(connection) \
	LP1(0x9c, LONG, OT_GetError, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_GetErrorText(connection) \
	LP1(0xa2, CONST_STRPTR, OT_GetErrorText, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_ErrorString(error) \
	LP1(0xa8, CONST_STRPTR, OT_ErrorString, LONG, error, d0, , OPENTLS_BASE_NAME)

#define OT_GetProtocol(connection) \
	LP1(0xae, LONG, OT_GetProtocol, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_GetCipher(connection) \
	LP1(0xb4, CONST_STRPTR, OT_GetCipher, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_GetALPN(connection) \
	LP1(0xba, CONST_STRPTR, OT_GetALPN, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#define OT_GetPeerFingerprint(connection, sha256) \
	LP2(0xc0, LONG, OT_GetPeerFingerprint, struct OTConnection *, connection, a0, UBYTE *, sha256, a1, , OPENTLS_BASE_NAME)

#define OT_GetPeerCertificate(connection, buffer, length) \
	LP3(0xc6, LONG, OT_GetPeerCertificate, struct OTConnection *, connection, a0, APTR, buffer, a1, LONG, length, d0, , OPENTLS_BASE_NAME)

#define OT_Random(buffer, length) \
	LP2(0xcc, LONG, OT_Random, APTR, buffer, a0, LONG, length, d0, , OPENTLS_BASE_NAME)

#define OT_Accelerated() \
	LP0(0xd2, ULONG, OT_Accelerated, , OPENTLS_BASE_NAME)

#define OT_GetErrorDetail(connection) \
	LP1(0xd8, LONG, OT_GetErrorDetail, struct OTConnection *, connection, a0, , OPENTLS_BASE_NAME)

#endif
