#!/usr/bin/env python3
"""Writes opentls.library's call headers from one table: clib/opentls_protos.h,
inline/opentls.h (GCC), fd/opentls_lib.fd, and the library's register entry
points and vector list (library/ot_entries.h, library/ot_vectors.h). The table is API version 1, frozen 9 Oct 2026:
new calls go at the end, nothing above them moves.
MIT, Copyright (c) 2026 Dalsin Limited."""
import os, sys

C, X, S = "struct OTContext *", "struct OTConnection *", "struct OTSession *"
CALLS = [
    ("OT_Version", "ULONG", []),
    ("OT_NewContext", C, [("CONST struct OTContextConfig *", "config", "a0"), ("LONG *", "error", "a1")]),
    ("OT_FreeContext", "VOID", [(C, "context", "a0")]),
    ("OT_AddTrustFile", "LONG", [(C, "context", "a0"), ("CONST_STRPTR", "path", "a1")]),
    ("OT_AddTrustPEM", "LONG", [(C, "context", "a0"), ("CONST_APTR", "pem", "a1"), ("LONG", "length", "d0")]),
    ("OT_NewConnection", X, [(C, "context", "a0"), ("CONST_STRPTR", "hostname", "a1"), ("LONG *", "error", "a2")]),
    ("OT_FreeConnection", "VOID", [(X, "connection", "a0")]),
    ("OT_SetSocket", "LONG", [(X, "connection", "a0"), ("LONG", "socket", "d0"), ("struct Library *", "socketBase", "a1")]),
    ("OT_SetIOHook", "LONG", [(X, "connection", "a0"), ("struct Hook *", "hook", "a1")]),
    ("OT_SetALPN", "LONG", [(X, "connection", "a0"), ("CONST_STRPTR", "protocols", "a1")]),
    ("OT_SetVerify", "LONG", [(X, "connection", "a0"), ("LONG", "mode", "d0")]),
    ("OT_PinCertificate", "LONG", [(X, "connection", "a0"), ("CONST UBYTE *", "sha256", "a1")]),
    ("OT_SetSession", "LONG", [(X, "connection", "a0"), (S, "session", "a1")]),
    ("OT_Handshake", "LONG", [(X, "connection", "a0")]),
    ("OT_Read", "LONG", [(X, "connection", "a0"), ("APTR", "buffer", "a1"), ("LONG", "length", "d0")]),
    ("OT_Write", "LONG", [(X, "connection", "a0"), ("CONST_APTR", "buffer", "a1"), ("LONG", "length", "d0")]),
    ("OT_Pending", "LONG", [(X, "connection", "a0")]),
    ("OT_Close", "LONG", [(X, "connection", "a0")]),
    ("OT_GetSession", S, [(X, "connection", "a0")]),
    ("OT_FreeSession", "VOID", [(S, "session", "a0")]),
    ("OT_SessionResumed", "LONG", [(X, "connection", "a0")]),
    ("OT_GetError", "LONG", [(X, "connection", "a0")]),
    ("OT_GetErrorText", "CONST_STRPTR", [(X, "connection", "a0")]),
    ("OT_ErrorString", "CONST_STRPTR", [("LONG", "error", "d0")]),
    ("OT_GetProtocol", "LONG", [(X, "connection", "a0")]),
    ("OT_GetCipher", "CONST_STRPTR", [(X, "connection", "a0")]),
    ("OT_GetALPN", "CONST_STRPTR", [(X, "connection", "a0")]),
    ("OT_GetPeerFingerprint", "LONG", [(X, "connection", "a0"), ("UBYTE *", "sha256", "a1")]),
    ("OT_GetPeerCertificate", "LONG", [(X, "connection", "a0"), ("APTR", "buffer", "a1"), ("LONG", "length", "d0")]),
    ("OT_Random", "LONG", [("APTR", "buffer", "a0"), ("LONG", "length", "d0")]),
    ("OT_Accelerated", "ULONG", []),
    ("OT_GetErrorDetail", "LONG", [(X, "connection", "a0")]),
    # version 1, revision 1 (additive)
    ("OT_GetPeerName", "CONST_STRPTR", [(X, "connection", "a0")]),
]
BIAS = 30

def main(root):
    inc = os.path.join(root, "include")
    for d in ("clib", "inline", "fd"):
        os.makedirs(os.path.join(inc, d), exist_ok=True)
    head = "/* Generated by tools/gen_opentls_headers.py: do not edit. MIT, (c) 2026 Dalsin Limited. */\n"
    p = [head, "#ifndef CLIB_OPENTLS_PROTOS_H\n#define CLIB_OPENTLS_PROTOS_H\n\n",
         "#include <exec/types.h>\n#include <exec/libraries.h>\n#include <libraries/opentls.h>\n\n"]
    i = [head, "#ifndef INLINE_OPENTLS_H\n#define INLINE_OPENTLS_H\n\n",
         "#ifndef __INLINE_MACROS_H\n#include <inline/macros.h>\n#endif\n\n",
         "#ifndef OPENTLS_BASE_NAME\n#define OPENTLS_BASE_NAME OpenTLSBase\n#endif\n\n"]
    f = ["* opentls.library, API version 1. Generated by tools/gen_opentls_headers.py\n",
         "##base _OpenTLSBase\n##bias %d\n##public\n" % BIAS]
    v = [head, "/* opentls.library's vectors after the four standard ones, in order. */\n"]
    for k, (name, rt, args) in enumerate(CALLS):
        off = BIAS + 6 * k
        decl = ", ".join("%s%s%s" % (t, "" if t.endswith("*") else " ", n) for t, n, r in args) or "VOID"
        p.append("%s %s(%s);\n" % (rt, name, decl))
        f.append("%s(%s)(%s)\n" % (name, ",".join(n for t, n, r in args), "/".join(r for t, n, r in args)))
        v.append("    (APTR)LIB_%s,\n" % name)
        nr = rt == "VOID"
        mac = "LP%d%s" % (len(args), "NR" if nr else "")
        parts = ["0x%x" % off] + ([] if nr else [rt.replace("CONST_STRPTR", "CONST_STRPTR")]) + [name]
        for t, n, r in args:
            parts += [t.strip(), n, r]
        parts += ["", "OPENTLS_BASE_NAME"]
        params = ", ".join(n for t, n, r in args)
        i.append("#define %s(%s) \\\n\t%s(%s)\n\n" % (name, params, mac, ", ".join(parts)))
    f.append("##end\n")
    p.append("\n#endif\n")
    i.append("#endif\n")
    for path, text in (("clib/opentls_protos.h", p), ("inline/opentls.h", i), ("fd/opentls_lib.fd", f)):
        with open(os.path.join(inc, path), "w") as fh:
            fh.write("".join(text))
    os.makedirs(os.path.join(root, "library"), exist_ok=True)
    with open(os.path.join(root, "library", "ot_vectors.h"), "w") as fh:
        fh.write("".join(v))
    e = [head, "/* opentls.library's entry points: registers in, the C calls of\n"
               " * src/opentls/ot_core.c out. Included by library/opentls_lib.c. */\n"]
    for name, rt, args in CALLS:
        params = ["REG(%s, %s%s%s)" % (r, t, "" if t.endswith("*") else " ", n) for t, n, r in args]
        params.append("REG(a6, struct Library *base)")
        call = "%s(%s)" % (name, ", ".join(n for t, n, r in args))
        body = "(void)base; %s%s;" % ("" if rt == "VOID" else "return ", call)
        e.append("static %s LIB_%s(%s)\n{ %s }\n" % (rt, name, ", ".join(params), body))
    with open(os.path.join(root, "library", "ot_entries.h"), "w") as fh:
        fh.write("".join(e))

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
